### ISSUE TITLE
API v1 issue: A lot of false positive results

### ISSUE THREAD

**Issue by martinrevert** [estemendoza/service.subtitles.argenteam#3]
Hi Esteban!

This doesn't happens always and it is not a direct add-on/service problem but the API is responding with a lot of garbage to some strings. I've checked an it happens if I send a raw request to the API, the subtitle service or even the web site search.

It is not a high priority issue but it is a very disturbing one, specially because depending on some underlaying conditions the real positive results are not the first of the list.

By example the movie "Frank", which is posted to the API as Frank+2014 returns all this

...
18:28:33 T:140530725943040   DEBUG: ### [**main**] - Search_argenteam='{'mansearch': False, 'episode': '', 'temp': False, 'title': 'Frank', 'season': '', 'tvshow': '', 'rar': False, 'year': '2014', 'file_original_path': u'smb://PCH-A110/share/Video/Frank.2014.LIMITED.720p.BluRay.x264-GECKOS.mkv', '3let_language': ['eng', 'spa', 'spa', 'spa']}', filename='Frank.2014.LIMITED.720p.BluRay.x264-GECKOS', addon_version=0.6.0
18:28:33 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/search?q=Frank+2014
18:28:33 T:140531913541824   DEBUG: ------ Window Deinit (VideoOSD.xml) ------
18:28:34 T:140530725943040  NOTICE: {"results":[{"id":78880,"title":"Kingdom","year":2014,"type":"tvshow","summary":"La serie se centra en un gimnasio de artes marciales en Venice Beach. Nick Jonas (Smash) y Matt Lauria (Friday Night Lights) serán los actores que interpretarán a los luchadores. Al drama dentro del ring se sumarán los problemas personales, como la prostitución de la madre de unos de los protagonistas.\r\nEntre otros actores: Frank Grillo (Captain America: The Winter Soldier), Kiele Sanchez (The Purge: Anarchy) y Jonathan Tucker (Parenthood). La serie está creada por Byron Balasco y Endemol Studio y es emitida por DirecTV.","imdb":"3673794","tvdb":"283761","poster":"http://www.argenteam.net/resources/covers/thumbs/3193334c44674e2fa60aa7ca866d49a3.jpg","seasons":1},{"id":79394,"title":"Frank (2014)","type":"movie","summary":"Jon (Gleeson), un joven aspirante a m&uacute;sico, se une a un grupo de exc&eacute;ntricos m&uacute;sicos pop liderado por el enigm&aacute;tico Frank (Fassbender) y su neur&oacute;tica compa&ntilde;era Clara (Gyllenhaal).","imdb":"1605717","poster":"http://www.argenteam.net/resources/covers/thumbs/93f5d108a9cf85148260d922664b7f4e.jpg"},{"id":80081,"title":"Blended (2014)","type":"movie","summary":"Después de una desastrosa cita a ciegas, los padres solteros Lauren (Drew Barrymore) y Jim (Adam Sandler) se muestran de acuerdo en una sola cosa: no desean volver a verse nunca más. Pero cuando contratan, cada uno por su lado, unas fabulosas vacaciones familiares con sus respectivos hijos, ambos se encuentran destinados sin remedio a compartir durante una semana una suite en un lujoso resort resort de recreo familiar en África dedicado a los safaris.","imdb":"1086772","poster":"http://www.argenteam.net/resources/covers/thumbs/f9d0fdce5b31f93bed882abbad73781c.jpg"},{"id":79133,"title":"The Normal Heart (2014)","type":"movie","summary":"En la época de mayor virulencia del SIDA, se ignoraba casi todo sobre una enfermedad que se calificó como \"el cáncer gay\". El film cuenta cómo la sociedad estadounidense fue asimilando la expansión de la gran epidemia. El guionista Larry Kramer traslada a la pantalla su propia experiencia vital en Nueva York a comienzos de los años 80.","imdb":"1684226","poster":"http://www.argenteam.net/resources/covers/thumbs/827216143d4c40742779f32293cd6c21.jpg"},{"id":80083,"title":"The Purge: Anarchy (2014)","type":"movie","summary":"El crimen hace estragos en Estados Unidos y las c&aacute;rceles est&aacute;n llenas. El gobierno decide que una noche al a&ntilde;o, durante doce horas, cualquier actividad criminal, incluso el asesinato, ser&aacute; legal. No se puede llamar a la polic&iacute;a, los hospitales no admiten pacientes, los ciudadanos deben arregl&aacute;rselas solos porque cometer un delito no est&aacute; castigado. Durante esa noche plagada de violencia, una familia debe decidir c&oacute;mo actuar cuando un extra&ntilde;o llama a la puerta.","imdb":"2975578","poster":"http://www.argenteam.net/resources/covers/thumbs/15f3b480e934be12270b0bd2f6bc2798.jpg"},{"id":81423,"title":"A Walk Among the Tombstones (2014)","type":"movie","summary":"Matt Scudder, un expolicía de Nueva York, trabaja como detective privado a pesar de que no tiene licencia. Cuando accede a regañadientes a ayudar a un traficante de heroína a cazar a los hombres que secuestraron y asesinaron brutalmente a su esposa, descubre que no es la primera vez que esos hombres han cometido este tipo de crímenes. Entonces decide recorrer las calles de Nueva York para detener a los asesinos antes de que vuelvan a matar.","imdb":"0365907","poster":"http://www.argenteam.net/resources/covers/thumbs/fa7e6816883758ae0f67b597fbde0129.jpg"},{"id":78844,"title":"Sin City: A Dame to Kill For (2014)","type":"movie","summary":"Los directores Frank Miller (&#39;The Spirit&#39;) y Robert Rodriguez (&#39;Machete&#39;), vuelven a rodar juntos la secuela de &#39;Ciudad del pecado&#39;, aunque en esta ocasi&oacute;n no estar&aacute;n acompa&ntilde;adados de Quentin Tarantino (&#39;Malditos bastardos&#39;).\r\n\r\nLa historia vuelve a estar ambientada en la oscura y peligrosa Sin City, y gira entorno a Dwight McCarthy (Josh Brolin, &#39;Oldboy&#39;) quien busca vengarse de su ex novia, Ava Lord, personaje interpretado por Eva Green (&#39;300: El origen de un imperio&#39;). Esta misteriosa e imponente mujer abandon&oacute; a Dwight para casarse con el poderoso y multimillonario Damien Lord y ahora ha regresado para traerle m&aacute;s problemas.\r\n\r\nPor otra parte, la joven bailarina y stripper del bar Kadies, Nancy Callahan (Jessica Alba, &#39;El demonio bajo la piel&#39;) tratar&aacute; de olvidar la p&eacute;rdida del agente John Hartigan (personaje interpretado por Bruce Willis en &#39;Frank Miller&#39;s Sin City - Ciudad del pecado&#39;), el cual la salv&oacute; en dos ocasiones de ser violada.","imdb":"0458481","poster":"http://www.argenteam.net/resources/covers/thumbs/1d5ec200dd97f41fe7c0333ed7bd0f6f.jpg"},{"id":79986,"title":"Deepsea Challenge 3D (2014)","type":"movie","summary":"Crónica de las experiencias subacuáticas del cineasta James Cameron dentro de las fosas oceánicas más profundas del planeta.","imdb":"2332883","poster":"http://www.argenteam.net/resources/covers/thumbs/55fa96da72a8ae655904645d0181bd20.jpg"}],"total":8,"offset":0}
18:28:34 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/tvshow?id=78880
18:28:34 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=78882
18:28:35 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:35 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79073
18:28:36 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:36 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79074
18:28:36 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:36 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79075
18:28:37 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:37 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79076
18:28:37 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:37 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79077
18:28:38 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:38 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79078
18:28:38 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:38 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79079
18:28:39 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:39 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79080
18:28:39 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:39 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/episode?id=79081
18:28:40 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:40 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=79394
18:28:40 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:40 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=80081
18:28:41 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:41 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=79133
18:28:42 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:42 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=80083
18:28:42 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:42 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=81423
18:28:43 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:43 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=78844
18:28:43 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:43 T:140530725943040   DEBUG: ### [ArgenteamUtilities] - Getting url: http://argenteam.net/api/v1/movie?id=79986
18:28:44 T:140530725943040   DEBUG: ### [**main**] - Resultados encontrados...
18:28:44 T:140530725943040    INFO: CPythonInvoker(3, /home/martin/.kodi/addons/service.subtitles.argenteam/service.py): script successfully run
18:28:44 T:140530314897152   DEBUG: WaitOnScriptResult- plugin returned successfully
18:28:44 T:140530725943040    INFO: Python script stopped
...

![screenshot from 2015-01-08 18 36 08](https://cloud.githubusercontent.com/assets/955927/5671329/b36e2b66-9765-11e4-82d8-9b1a897b0d96.png)
![screenshot from 2015-01-08 18 36 54](https://cloud.githubusercontent.com/assets/955927/5671330/b36e24ea-9765-11e4-8fb0-a3244a9589d1.png)

**Comment by estemendoza** [comment]
The results are fine, it just that the API also search other fields like Director, which is not displayed on the JSON response, but it is taken account when doing the search.

Closing as invalid, but thanks for reporting it!
