### ISSUE TITLE
Baja siempre el mismo sub

### ISSUE THREAD

**Issue by diego-garber** [estemendoza/service.subtitles.argenteam#4]
Hola, no se bien como contactarte de otra manera asi que te lo paso por aca. Tengo hace un par de dias un problema con el addon que hace que a pesar de buscar y seleccionar el sub correctamente, al bajarlo baja siempre el mismo, uno que no tiene nada que ver. Argenteam habra cambiado su API/Interface? Porque sigo con la misma version de Addon de siempre y encima me pasa en los 2 xbmc que tengo instalados. Gracias!!
Gran laburo el tuyo, che.. avisame si necesitas ayuda que yo codeo tambien.

**Comment by estemendoza** [comment]
Sí, eso es un bug con la versión actual del plugin. Otro pibe me subió un fix y ya lo apliqué, pero también yo he metido cambios en el plugin para que labure con la API nueva de argenteam.

Entonces, te iba a pedir que si podés, te bajes el código y lo reemplaces en tu xbmc/kodi y te fijes como funciona, ¿entendes?

Si necesitas ayuda avisame.

Saludos

**Comment by diego-garber** [comment]
Ok, para bajarlo e instalarlo lo bajo directamente de Github con el boton
de "Download ZIP" y despues lo instalo desde el zip en el menu de Addons? O
hay algun otro metodo mejor?

2015-01-12 15:34 GMT-03:00 Esteban Mendoza notifications@github.com:

> Sí, eso es un bug con la versión actual del plugin. Otro pibe me subió un
> fix y ya lo apliqué, pero también yo he metido cambios en el plugin para
> que labure con la API nueva de argenteam.
> 
> Entonces, te iba a pedir que si podés, te bajes el código y lo reemplaces
> en tu xbmc/kodi y te fijes como funciona, ¿entendes?
> 
> Si necesitas ayuda avisame.
> 
> Saludos
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/estemendoza/service.subtitles.argenteam/issues/4#issuecomment-69620029
> .

## 

[image: OLX]

Diego Garber
Engineering Team Leader - Engineering Team
Infrastructure Team
OLX Inc.
Buenos Aires, Argentina
 Phone: +54-11-47756696
Mobile: +54-11-55806064
Skype: diegarber
E-mail: diego.garber@olx.com nlastname@olx.com

**Comment by estemendoza** [comment]
La verdad que no sé si te funciona lo del zip, probalo, creería que sí.

Si no te funciona, busca donde tenés la configuración del usuario (http://kodi.wiki/view/Userdata) y de ahí te volvés un directorio arriba y buscas la carpeta que dice "addons" y ahí debe estar una que dice "service.subtitles.argenteam", reemplaza el contenido de esa carpeta con el del zip.

**Comment by diego-garber** [comment]
Gracias!

2015-01-12 16:47 GMT-03:00 Esteban Mendoza notifications@github.com:

> La verdad que no sé si te funciona lo del zip, probalo, creería que sí.
> 
> Si no te funciona, busca donde tenés la configuración del usuario (
> http://kodi.wiki/view/Userdata) y de ahí te volvés un directorio arriba y
> buscas la carpeta que dice "addons" y ahí debe estar una que dice
> "service.subtitles.argenteam", reemplaza el contenido de esa carpeta con el
> del zip.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/estemendoza/service.subtitles.argenteam/issues/4#issuecomment-69632831
> .

## 

[image: OLX]

Diego Garber
Engineering Team Leader - Engineering Team
Infrastructure Team
OLX Inc.
Buenos Aires, Argentina
 Phone: +54-11-47756696
Mobile: +54-11-55806064
Skype: diegarber
E-mail: diego.garber@olx.com nlastname@olx.com

**Comment by martinrevert** [comment]
Hola @diego-garber, solo para chequear...migraste a Kodi hace poco?

**Comment by diego-garber** [comment]
Así es.

**Comment by martinrevert** [comment]
@diego-garber  Ok. No dejes de confirmarle a Esteban si el addon que instalás manualmente te soluciona el problema. Saludos!

PD: Ojo con las versiones, si Esteban no cambia la version del addon y agrega/modifica algo en el código antes del release definitivo te va a quedar el addon sin actualizar hasta que haya una nueva versión.

**Comment by diego-garber** [comment]
Anduvo!

**Comment by martinrevert** [comment]
@estemendoza Yo creo que este issue lo podés matar tranquilamente. Abrazo.

**Comment by estemendoza** [comment]
Dale, lo cierro por ahora, cualquier cosa volvelo a abrir. Saludos!
