### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by alfredoivan** [estemendoza/service.subtitles.argenteam#7]
The subtitles are not working right now.

**Comment by fedux** [comment]
It seems https://github.com/estemendoza/service.subtitles.argenteam/pull/5 should solve the problem, however, the latest available version in the official repos, https://kodi.tv/addons/browse?keyword=argenteam does not include the fix yet. @estemendoza, can you please update it?

**Comment by estemendoza** [comment]
I just released a new version of the plugin, now we have to wait for Kodi to pick it up from this repo

**Comment by fedux** [comment]
Mmm... I don't think waiting will be enough. It seems you either have to create a PR or open an issue as explained here: https://kodi.wiki/view/Submitting_Add-ons#Github

If you want me to do it myself let me know.

**Comment by estemendoza** [comment]
@fedux Thanks for your help, so yes, if you can do a PR for the plugin, I would appreciate it.
